CFLAGS=-Wall -g

ex3: ex3.c chapter0.c
	gcc -Wall -g ex3.c -o ex3
	gcc -Wall -g chapter0.c -o chapter0

ex7: ex7.c 
	gcc -Wall -g ex7.c -o ex7

ex8: ex8.c
	gcc -Wall -g ex8.c -o ex8

ex9: ex9.c
	gcc -Wall -g ex9.c -o ex9

ex15: ex15.c
	gcc -Wall -g ex15.c -o ex15

ex16: ex16.c
	gcc -Wall -g ex16.c -o ex16


clean:
	rm -f chapter0 ex3 ex7 ex8 ex9
	rm -f ex15 ex16